concurrency = 12
max_diagram_symbols = 65535
diagram_recursion_depth = 2

[input]
directory = "../beholderFPS"
ignore = ["vendor", ".git", ".gopath", "cicd", "docs"]

[[output]]
format = "html"
directory = "docs/beholderFPS"

[[output]]
format = "markdown"
directory = "docs/beholderFPS_md"
