concurrency = 12
max_diagram_symbols = 999999

[input]
directory = "../beholderFPS"
ignore = ["vendor", ".git", ".gopath", "cicd"]

[[output]]
format = "html"
directory = "docs/beholderFPS"

[[output]]
format = "markdown"
directory = "docs/beholderFPS_md"
