concurrency = 12
max_diagram_symbols = 999999

[input]
directory = "../playtranslate"
ignore = ["vendor", ".git", ".gopath", "venv", "__pycache__"]

[[output]]
format = "html"
directory = "docs/playtranslate"

[[output]]
format = "markdown"
directory = "docs/playtranslate_md"
